# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df62730d767eb9d8a0c29c004d8606f5e953e393f5b1262c607babd019187a0e214cccf595b281a61cd167b68aff44d75fee3ef98684acb63f21846a679c33bb

test:
  secret_key_base: 189a7bb01c934470c95291899ed6905017fc5bff66411731e51ef5d6baa9693ad639b3e8666e17329236caaf48932c273f2d5e493859385c184e718cbf7e6543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
